server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hoha"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Ho1hai*ha
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 7200 # in second
  refreshable-duration: 36000 # in seconds



